### ISSUE TITLE
[Help] how do I add axes on scatterplot visualisation in code ?

### ISSUE THREAD

**Issue by chloePoi** [MaximeCordeil/IATK#15]
Hello,

I follow the end of this tutorial (https://vimeo.com/320646218). I would like to add axes using code.

How can I do that ?

Thanks for your help

**Comment by danieljharris** [comment]
This might not be a perfect example as it using a proposed new feature (Realtime Data Source). But [this code](https://github.com/philfleck/IATK/blob/icg_fleck_realtime_datasource_and_replicator/Assets/IATK/Scripts/Demo/RealtimeDataDemo.cs#L74-L140) under the "CreateVisFromSource" function contains everything you should need to configure a scatterplot visualisation from code, including adding axes (aka dimensions).
