### ISSUE TITLE
How to Identify version of Unity and VRTK to use with IATK at any point in time?

### ISSUE THREAD

**Issue by CodeChopper** [MaximeCordeil/IATK#16]
Hi. Is there a way to know which version of Unity and VRTK to use with IATK for any given commit?

For example, in the excellent talk posted on vimeo, I believe the Unity version was 2017 and VRTK was presumably an earlier version at that time. However, both VRTK and IATK (and Unity) are constantly moving forward. Is there a README or text file within the IATK repository that provides the current versions of VRTK and Unity (used at the time of the commit)?  That way if somebody clones the IATK repo at any given time, they will know which version of Unity and VRTK to use.

Thank you.

**Comment by danieljharris** [comment]
The file located at "ProjectSettings/ProjectVersion.txt" contains the current Unity version used.

As for VRTK from what I can tell most of the integration needs to be added after downloading the repository and aren't actually included. So, you should be able to use any VRTK version you want to, as you'll need to add the integrations in yourself anyway.

**Comment by kmilo9999** [comment]
Hello, 
I just tested IATK + Unity 2019.2.8 + VRTK 4 and it doesnt seem to work. I got multiple compiling error on the AR-Core package.

**Comment by danieljharris** [comment]
The latest version in master should be working with "Unity 2021.3.4f1". Also master now has integrated support for VRTK v4 meaning you don't need to install VRTK yourself. To get the project working just download the repo, install the MapBox plugin (link given under "requirements" section of README.md).

An example scene called "VRTK v4 Scene" can be used to see a fully working environment that uses IATK data visualisations that can be interacted with using any [OpenXR compatible headset](https://www.khronos.org/conformance/adopters/conformant-products/openxr). There is also now a step by step tutorial on how to get the "VRTK v4 Scene" working: [VR_TUTORIAL.md](https://github.com/MaximeCordeil/IATK/blob/master/Documentation/VR_TUTORIAL.md).
