### ISSUE TITLE
How to interact with elements of the visualization?

### ISSUE THREAD

**Issue by peterclemenko** [MaximeCordeil/IATK#25]
I'm trying to use MRTK as the ux layer of my app and IATK for the viz. I'm curious how to interact with data in the IATK plots using MRTK, so for example with a hololens i can touch a data point and get details.

**Comment by danieljharris** [comment]
Hi,

I would recommend you start by looking at how the "brushing and linking" component works, as this is the closest thing IATK has to the functionally you describe. There is a [video that briefly goes over it](https://vimeo.com/320646218#t=7169s) and [code for it under "BrushingAndLinking.cs"](https://github.com/MaximeCordeil/IATK/blob/master/Assets/IATK/Scripts/Controller/BrushingAndLinking.cs) and is probably the best place to start looking.

Unfortunately, I've not worked with the BigMesh data points in IATK so can't give more guidance (Only recently started learning IATK). Though if I find any additional information about it I will let you know 🙂.

On a side note, if you are looking to add a lot of AR/VR functionality with IATK I'd also recommend you take a look at [my draft branch](https://github.com/danieljharris/IATK/tree/2020_VRTK), it adds functionality to grab (hold), move, scale, and interact with the min & max filter sliders for scatterplot visualisations using the VRTK v4 library and should work with any OpenXR compatible device including HoloLens (although this has not yet been tested and the branch is still in development).

Hope this helps 🙂
