### ISSUE TITLE
Versions?

### ISSUE THREAD

**Issue by eeleeml** [MaximeCordeil/IATK#34]
I've tried to run this but i don't now which versions to use...
It says Unity 2021.3.3f, but then with the VRTK it asks for another Unity version... 
No combination is working

**Comment by danieljharris** [comment]
The latest version in master should be working with "Unity 2021.3.4f1". Also master now has integrated support for VRTK v4 meaning you don't need to install VRTK yourself. To get the project working just download the repo, install the MapBox plugin (link given under "requirements" section of README.md).

An example scene called "VRTK v4 Scene" can be used to see a fully working environment that uses IATK data visualisations that can be interacted with using any [OpenXR compatible headset](https://www.khronos.org/conformance/adopters/conformant-products/openxr).

Please note to get "VRTK v4 Scene" working you will need to import the sample from Package Manager > Packages: In Project > Tilia Input UnityInputSystem > Samples > GenericXR > Import.

Hope this helps, let me know if you have any further issues getting it working :)

**Comment by danieljharris** [comment]
I've just written a tutorial with a step by step guide to get the "VRTK v4 Scene" working: [VR_TUTORIAL.md](https://github.com/MaximeCordeil/IATK/blob/master/Documentation/VR_TUTORIAL.md)
