### ISSUE TITLE
Error to start project IATK

### ISSUE THREAD

**Issue by adilsonv77** [MaximeCordeil/IATK#37]
I'm trying to get IATK to work. 
1. Download the project from Github
2. Install Unity 2021.3.4f1
3. Open the project (shows the window below, then Enter Safe Mode

![image](https://github.com/MaximeCordeil/IATK/assets/3033544/54f22195-34ba-465f-882c-4ede68816ee2)

4. Exit Safe Mode
5. Download Mapbox and imported
6. Close Unity
7. Open again and show the same window above

After open Unity, it shows the compiler error "Library\PackageCache\com.unity.test-framework@1.1.31\UnityEditor.TestRunner\Api\IErrorCallbacks.cs(1,1): error CS1056: Unexpected character '"

What I'm doing wrong?

**Comment by adilsonv77** [comment]
I solved the message error updating Test framework to version 1.3.8.

Now, the messages error are 
- Assets\GoogleARCore\SDK\Scripts\ARCoreBackgroundRenderer.cs(43,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found
- Assets\UnityARInterface\Scripts\ARCoreInterface.cs(51,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found
- Assets\UnityARInterface\Scripts\ARKitInterface.cs(26,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found
- Assets\UnityARInterface\ARRemote\Scripts\ARRemoteEditorInterface.cs(40,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found

I try now to install and update the packages related to these messages.

**Comment by adilsonv77** [comment]
For register:
- I changed Packages\manifest.json "com.unity.test-framework": "1.1.31", > "1.3.8"

When I import Mapbox, unselect all boxes related to AR: 
- GoogleARCore
- MapBoxAR
- UnityARInterface
- UnityARKitPlugin

Now, menus ITAK are visible. I can start to study. Thanks !!!!

**Comment by danieljharris** [comment]
Glad you managed to fix the issue yourself, let me know if you have any more trouble with it :)
