### ISSUE TITLE
Values in Axis 

### ISSUE THREAD

**Issue by adilsonv77** [MaximeCordeil/IATK#38]
I'm following the tutorial (https://vimeo.com/320646218) and this point I'm creating a scatterplot.

The values from the Axis are different from my work. As seen in the figure, there is no value in Date axis. How can I enable this appearance?

![image](https://github.com/MaximeCordeil/IATK/assets/3033544/a5d6fec0-babc-4dd2-8301-e93e78456993)

**Comment by adilsonv77** [comment]
Where do we download the tutorial folder? Is it still available?

**Comment by danieljharris** [comment]
I'm not sure if this contains the required files but this is the best place to look: https://github.com/MaximeCordeil/IATK/tree/master/Assets/IATK/Tutorial

Let me know if you find what you need or have any other questions :)

**Comment by adilsonv77** [comment]
It seems is not the same presented in the Vimeo Tutorial... It doesnt matter, now....  There are some problems when render the graphs if we compare between the tutorial and our local work. As I demonstrated before, the values of X axis are not rendering. When I try the scatterplot mattrix, the leading diagonal is not showing (see the image below).

![image](https://github.com/MaximeCordeil/IATK/assets/3033544/70c88220-a56f-4ab4-8c45-6e8af848edfd)

Maybe there are some differences because the Unity versions. However, I'm using the 2021.3.4f1.

Thanks in advance for all your help.

**Comment by adilsonv77** [comment]
Close and Open the scene again, it rendered....

**Comment by adilsonv77** [comment]
Close and Open the scene again, it rendered....
