### ISSUE TITLE
New scenes or visualizations with Tilia

### ISSUE THREAD

**Issue by adilsonv77** [MaximeCordeil/IATK#41]
Hallo... 

At https://github.com/MaximeCordeil/IATK/issues/34 is explained that you created a tutorial to use VRTK.

However, it is not enough to create new visualizations!!! Please, we need a documentation to tell us which are the steps to follow then you have an interactable scatterplot.

Also, a new question: is it possible to touch a specific point ? I need to create a window to show some information of that point.

**Comment by danieljharris** [comment]
Hi,

There is also the tutorial at: https://github.com/MaximeCordeil/IATK/blob/master/Documentation/Visualisation_Tutorial.md and there are additional video tutorials on the main readme: https://github.com/MaximeCordeil/IATK?tab=readme-ov-file#tutorial

Sadly, I do not have the time to create any further documentation myself.

And yes it is possible to detect interactions with specific points, as shown in the functionality of brushing and linking: https://github.com/MaximeCordeil/IATK?tab=readme-ov-file#brushing-and-linking
