### ISSUE TITLE
Not able to see the IATK optiion in Heirarchy window

### ISSUE THREAD

**Issue by mahtabmd** [MaximeCordeil/IATK#8]
Hi Maxime,

I added the repository the folder IATK , imported it by drag and drop in "ASSET" but I am not able to see the IATK option in Heirarchy window(  to add datset and iatk visualization)

[attached image below]

May you please suggest where m i going wrong. I am new beginner with unity and IATK.

Thanks,
Mahtab 
![iatk_issue](https://user-images.githubusercontent.com/40524079/54878734-c9b8db80-4e56-11e9-8204-d481495ca5c2.png)

**Comment by MaximeCordeil** [comment]
Hi Mathab,

you should open the IATK folder as a Unity project, not paste it into the Asset folder of an existing project. Currently IATK is within your Asset folder, but the root folder should be IATK.

Decompress IATK again somewhere and open it as a Unity project.
I see you're using Unity 2018, you need to pull the 2018 branch.

Best regards
Maxime

**Comment by mahtabmd** [comment]
Thanks Maxime, It worked :)
