### ISSUE TITLE
Requirements seem incompatible with VRTK

### ISSUE THREAD

**Issue by Permiek** [MaximeCordeil/IATK#9]
Your requirements list Unity 2017 and VRTK. VRTK lists 2018.3.10f1 and above. Can i move to unity 2018 for both IATK and VRTK ?

Thanks

**Comment by MaximeCordeil** [comment]
Hello Permiek. have you been successful? There is an IATK fo Unity 2018 that you could try as well.

Regards
Maxime

**Comment by Permiek** [comment]
Thanks for reply Maxime. I am happy to try the IATK version for Unity 2018, how do I get it ?
I see you have updated for Unity 2019 , can I just move to that ?

Thanks

**Comment by MaximeCordeil** [comment]
Sorry for late reply - yes it works with 2019

**Comment by passantfarouk** [comment]
Hi Maxime, I am using unity 2020.3.9 and importing IATK and want to use it for interactive data visualisation in AR using the hololens 1st gen and i have errors related to unity ARinterface and ARcore is it related to the upgrade of the unity version or i forgot to import a package? 

here is the errors that appear to me 
![Screenshot (119)](https://user-images.githubusercontent.com/74142045/119563950-7af58c00-bda8-11eb-8a31-e4bf8dd60a9b.png)

**Comment by atzanteotl** [comment]
Hi - are you able to outline a bare-minimum project to reproduce this issue? It looks like it could be incompatibility between certain modules and the Unity version.

**Comment by danieljharris** [comment]
@passantfarouk If your still having issues getting IATK to work with Unity 2020 see my PR as it should fix your issues: https://github.com/MaximeCordeil/IATK/pull/21

Also make sure your importing "MapBox Unity Plugin" alongside IATK as it is a dependency. Or alternatively if you don't want to use the map integration just delete the file at "Assets\IATK\Scripts\Util\MapVisualisation.cs".
